# Generated by Django 5.1.2 on 2024-10-22 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.BigIntegerField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_category', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.FloatField(default=0.0)),
                ('load_unit', models.CharField(max_length=30)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('time_departure', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.client')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.fuel')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.vehicle')),
            ],
        ),
    ]
