# Generated by Django 5.1.2 on 2024-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='earned_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fuelexpense',
            name='expense_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='time_departure',
            field=models.DateTimeField(),
        ),
    ]
