# Generated by Django 5.1.2 on 2024-10-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_fuel_earned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
