# Generated by Django 5.1.2 on 2024-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_shipment_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
